### PR TITLE
Improved Github auto-importer.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by chaosagent** [comment]
You should use requirements.txt in the Dockerfile...

**Comment by ghost** [comment]
It's a hack to avoid having to install all dependencies when I need a new dependency.

Docker will cache the command that explicitly lists all of the dependencies, and then runs the requirements.txt installation every time it rebuilds.

We can remove it later :P

**Comment by chaosagent** [comment]
Oh rip okay then
Looks OK, although having a git clone thing in a webapp container seems a bit dirty, so you might want to consider splitting the cloning/grading/problem-adding parts into another docker container, but thats probably just too much trouble

**Comment by mzhangARS** [comment]
whatever lol

**Pull request merged**
